name: 'Deployment Tests'

on:
  push:
    branches:
      - main
      - develop

jobs:
  ############################# Deployment Tests for GCP modules #####################################################
  MCP-tests:
    runs-on: ubuntu-latest

    env:
      working-directory: ./tests/gcp/deployment
      
    defaults:
      run:
        shell: bash
        working-directory: ${{env.working-directory}}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      # Install gcloud sdk and set the service account
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{secrets.GCP_SA_KEY}}
          export_default_credentials: true

      # Deploy google folders
      - name: Add IDs to GCP Folder Files
        run: |
          cd google_folder/resource
          sed -i "s/<folder_id>/folders\/${{secrets.GCP_FOLDER_ID}}/" folders.yaml
          SERVICE_ACCOUNT=$(echo $GOOGLE_CREDENTIALS | jq -r '.client_email')
          sed -i "s/<service_account>/$SERVICE_ACCOUNT/"  folders.yaml
          cat folders.yaml
          
      - name: Deploy Google folder 
        run: |
          cd google_folder
          terraform init
          terraform plan -out="./plan.tfplan"
          terraform apply plan.tfplan
          terraform plan -destroy -out="./destroy.tfplan"
          terraform apply destroy.tfplan

      # Deploy google projects
      - name: Add IDs to GCP Project Files
        run: |
          cd google_project/resource
          sed -i "s/<project_id>/${{secrets.GCP_PROJECT_ID}}-$(date +%y%m%d%H%M)//" projects.yaml
          sed -i "s/<folder_id>/folders\/${{secrets.GCP_FOLDER_ID}}/" projects.yaml
          sed -i "s/<billing_account>/${{secrets.GCP_BILLING_ACCOUNT}}/" projects.yaml
          SERVICE_ACCOUNT=$(echo $GOOGLE_CREDENTIALS | jq -r '.client_email')
          sed -i "s/<service_account>/$SERVICE_ACCOUNT"  projects.yaml
          cat projects.yaml
          
      - name: Deploy Google folder 
        run: |
          cd google_project
          terraform init
          terraform plan -out="./plan.tfplan"
          terraform apply plan.tfplan
          terraform plan -destroy -out="./destroy.tfplan"
          terraform apply destroy.tfplan

     