name: 'Delete Deployment Test Resources'

on:
  pull_request:
    branches:
      - main
    types: [opened]
  workflow_dispatch:
    inputs:
      resource:
        description: "Resource from deployment tests to destroy"
        required: true
        type: choice
        options:
          - projects
          - folders
        default: 'projects'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  destroy-folders:
    name: "Destroy folder"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' ||  github.event.inputs.resource == 'folders'
    env:
      working-directory: ./tests/gcp/deployment/google_folder
      TF_VAR_sub_folder_parent: staging

    defaults:
      run:
        shell: bash
        working-directory: ${{env.working-directory}}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      # Install gcloud sdk and set the service account
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{secrets.GCP_SA_EMAIL}}
          workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER}}
          token_format: 'access_token'
          access_token_lifetime: 1200s # 20 minutes

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Install python and required pip package
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install pyyaml

      - name: Add IDs to GCP Folder Files
        run: |
          cd resource
          sed -i "s/<folder_id>/folders\/${{secrets.GCP_FOLDER_ID}}/" folders.yaml
          sed -i "s/<service_account>/${{secrets.GCP_SA_EMAIL}}/"  folders.yaml
          cat folders.yaml

      - name: Import Folders to terraform state
        env:
          GCP_FOLDER_ID: ${{secrets.GCP_FOLDER_ID}}
        run: ./folder_import_script.sh

      - name: Destroy folders
        run: terraform destroy -auto-approve

  delete-projects:
    name: "Delete projects"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' ||  github.event.inputs.resource == 'projects'
    env:
      working-directory: ./tests/gcp/deployment/google_project

    defaults:
      run:
        shell: bash
        working-directory: ${{env.working-directory}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install gcloud sdk and set the service account
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{secrets.GCP_SA_EMAIL}}
          workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER}}
          token_format: 'access_token'
          access_token_lifetime: 1200s # 20 minutes

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Install python and required pip package
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: pip install pyyaml

      - name: Delete projects
        env:
          GCP_FOLDER_ID: ${{secrets.GCP_FOLDER_ID}}
        run: ./delete_projects.sh
